tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT=on-partial
  - before:
      cd /worskpace
      msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi /qn
      cd C:\Users\marco.davanzo\worskpace\AWS-Exampple

