AWSTemplateFormatVersion: "2010-09-09"
Description: Create a role for us to assume and create a resource
Parameters:
  BucketName:
    Type: String
    Default: "bucket-fun-sts-123"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
                AWS: "arn:aws:iam::137263334750:user/stsmachine-user"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17" 
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: [
                  !Sub "arn:aws:s3:::${BucketName}",
                  !Sub "arn:aws:s3:::${BucketName}/*"
                ]