#!/usr/bin/env bash

# Create our vpc
VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
--region us-east-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=cli-vpc}]' \
--query Vpc.VpcId \
--output text
)
# vpc-02e7a018736af1270

echo "VPC:" $VPC_ID 

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

echo "IGW:" $IGW_ID

# Attach an IGWi
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

# Create a new subnet
SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID \
--cidr-block "172.1.0.0/20" \
--query Subnet.SubnetId \
--output text
)

echo "Subnet:" $SUBNET_ID

# Auto assign IPv4
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch

# Get the rout table for the provided VPC
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text
)

echo "Route Table:" $RT_ID

# Explicity associate subnets
aws ec2 associate-route-table --route-table-id=$RT_ID \
--subnet-id $SUBNET_ID

# Add a route for our Route Table to our IGW
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID