AWSTemplateFormatVersion: 2010-09-09
Description: A sample bucket.
Resources:
  S3Bucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'